In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [26]:
train = pd.read_csv('train.csv', encoding = 'ISO-8859-1')

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (11,12,31) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [27]:
train.sample(5)

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,grafitti_status,compliance_detail,compliance
33579,54053,"Buildings, Safety Engineering & Env Department","O'Neal, Claude","CRAWFORD, SARAYA",17245.0,VAUGHAN,NaN,1232.0,DREXEL CT.,GRAND RAPIDS,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
83797,108828,Department of Public Works,"Hayes, Billy J","MORRIS, ORANETTA A",18320.0,AVON,NaN,1832.0,AVON,DETROIT,...,0.0,85.0,0.0,85.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
208087,241127,Detroit Police Department,"Borden, Kenyetta","HEANEY, WILLIAM",14474.0,SEVEN MILE,NaN,14474.0,E. SEVEN MILE,DETROIT,...,0.0,130.0,120.0,10.0,2010-02-16 00:00:00,PARTIAL PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
232561,266828,"Buildings, Safety Engineering & Env Department","Samaan, Neil J","daoud, emmanuel",9635.0,VAN DYKE,NaN,9635.0,van dyke,det,...,0.0,167.5,0.0,167.5,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
104888,130972,"Buildings, Safety Engineering & Env Department","Doetsch, James","CRAWFORD, JR., ALLPHONSO",11199.0,CHARLEMAGNE,NaN,2281.0,EDISON,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN

In [28]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250306 entries, 0 to 250305
Data columns (total 34 columns):
ticket_id                     250306 non-null int64
agency_name                   250306 non-null object
inspector_name                250306 non-null object
violator_name                 250272 non-null object
violation_street_number       250306 non-null float64
violation_street_name         250306 non-null object
violation_zip_code            0 non-null float64
mailing_address_str_number    246704 non-null float64
mailing_address_str_name      250302 non-null object
city                          250306 non-null object
state                         250213 non-null object
zip_code                      250305 non-null object
non_us_str_code               3 non-null object
country                       250306 non-null object
ticket_issued_date            250306 non-null object
hearing_date                  237815 non-null object
violation_code                250306 non-null object
violation_description         250306 non-null object
disposition                   250306 non-null object
fine_amount                   250305 non-null float64
admin_fee                     250306 non-null float64
state_fee                     250306 non-null float64
late_fee                      250306 non-null float64
discount_amount               250306 non-null float64
clean_up_cost                 250306 non-null float64
judgment_amount               250306 non-null float64
payment_amount                250306 non-null float64
balance_due                   250306 non-null float64
payment_date                  41113 non-null object
payment_status                250306 non-null object
collection_status             36897 non-null object
grafitti_status               1 non-null object
compliance_detail             250306 non-null object
compliance                    159880 non-null float64
dtypes: float64(13), int64(1), object(20)
memory usage: 64.9+ MB

In [29]:
train.describe()

,ticket_id,violation_street_number,violation_zip_code,mailing_address_str_number,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,payment_amount,balance_due,compliance
count,250306.000000,2.503060e+05,0.0,2.467040e+05,250305.000000,250306.000000,250306.000000,250306.000000,250306.000000,250306.0,250306.000000,250306.000000,250306.000000,159880.000000
mean,152665.543099,1.064986e+04,NaN,9.149788e+03,374.423435,12.774764,6.387382,21.494506,0.125167,0.0,268.685356,48.898986,222.449058,0.072536
std,77189.882881,3.188733e+04,NaN,3.602034e+04,707.195807,9.607344,4.803672,56.464263,3.430178,0.0,626.915212,222.422425,606.394010,0.259374
min,18645.000000,0.000000e+00,NaN,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,-7750.000000,0.000000
25%,86549.250000,4.739000e+03,NaN,5.440000e+02,200.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
50%,152597.500000,1.024400e+04,NaN,2.456000e+03,250.000000,20.000000,10.000000,10.000000,0.000000,0.0,140.000000,0.000000,25.000000,0.000000
75%,219888.750000,1.576000e+04,NaN,1.292725e+04,250.000000,20.000000,10.000000,25.000000,0.000000,0.0,305.000000,0.000000,305.000000,0.000000
max,366178.000000,1.415411e+07,NaN,5.111345e+06,10000.000000,20.000000,10.000000,1000.000000,350.000000,0.0,11030.000000,11075.000000,11030.000000,1.000000

In [30]:
train.isnull().any()

ticket_id                     False
agency_name                   False
inspector_name                False
violator_name                  True
violation_street_number       False
violation_street_name         False
violation_zip_code             True
mailing_address_str_number     True
mailing_address_str_name       True
city                          False
state                          True
zip_code                       True
non_us_str_code                True
country                       False
ticket_issued_date            False
hearing_date                   True
violation_code                False
violation_description         False
disposition                   False
fine_amount                    True
admin_fee                     False
state_fee                     False
late_fee                      False
discount_amount               False
clean_up_cost                 False
judgment_amount               False
payment_amount                False
balance_due                   False
payment_date                   True
payment_status                False
collection_status              True
grafitti_status                True
compliance_detail             False
compliance                     True
dtype: bool

In [31]:
train.dtypes

ticket_id                       int64
agency_name                    object
inspector_name                 object
violator_name                  object
violation_street_number       float64
violation_street_name          object
violation_zip_code            float64
mailing_address_str_number    float64
mailing_address_str_name       object
city                           object
state                          object
zip_code                       object
non_us_str_code                object
country                        object
ticket_issued_date             object
hearing_date                   object
violation_code                 object
violation_description          object
disposition                    object
fine_amount                   float64
admin_fee                     float64
state_fee                     float64
late_fee                      float64
discount_amount               float64
clean_up_cost                 float64
judgment_amount               float64
payment_amount                float64
balance_due                   float64
payment_date                   object
payment_status                 object
collection_status              object
grafitti_status                object
compliance_detail              object
compliance                    float64
dtype: object

In [32]:
#make the ticket id the index
train.index = train['ticket_id']

In [33]:
train.head()

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,grafitti_status,compliance_detail,compliance
ticket_id,,,,,,,,,,,,,,,,,,,,,
22056,22056,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","INVESTMENT INC., MIDWEST MORTGAGE",2900.0,TYLER,NaN,3.0,S. WICKER,CHICAGO,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
27586,27586,"Buildings, Safety Engineering & Env Department","Williams, Darrin","Michigan, Covenant House",4311.0,CENTRAL,NaN,2959.0,Martin Luther King,Detroit,...,0.0,855.0,780.0,75.0,2005-06-02 00:00:00,PAID IN FULL,NaN,NaN,compliant by late payment within 1 month,1.0
22062,22062,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","SANDERS, DERRON",1449.0,LONGFELLOW,NaN,23658.0,P.O. BOX,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
22084,22084,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","MOROSI, MIKE",1441.0,LONGFELLOW,NaN,5.0,ST. CLAIR,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN
22093,22093,"Buildings, Safety Engineering & Env Department","Sims, Martinzie","NATHANIEL, NEAL",2449.0,CHURCHILL,NaN,7449.0,CHURCHILL,DETROIT,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,NaN

In [34]:
#drop any values in compliance column that is null because null means not responsible
train.compliance = train.compliance.fillna(value=-1)

In [61]:
#Features to keep
features = ['fine_amount', 'admin_fee', 'state_fee', 'late_fee', 'discount_amount', 'clean_up_cost','judgment_amount']

In [62]:
x = train[features]

In [63]:
train.sample(5)

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,clean_up_cost,judgment_amount,payment_amount,balance_due,payment_date,payment_status,collection_status,grafitti_status,compliance_detail,compliance
ticket_id,,,,,,,,,,,,,,,,,,,,,
224532,224532,"Buildings, Safety Engineering & Env Department","Morris, John","Brooks, John",1545.0,EUCLID,NaN,13341.0,Tireman,Dearborn,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0
163514,163514,Department of Public Works,"Davis, Darlene","INC., CITIMORTGAGE",9130.0,BEACONSFIELD,NaN,1111.0,NORTHPOINT DR.,COPPELL,...,0.0,2780.0,2224.0,556.0,2014-10-22 00:00:00,PAID IN FULL,NaN,NaN,non-compliant by late payment more than 1 month,0.0
247214,247214,"Buildings, Safety Engineering & Env Department","ELLARD, EVERETT","Service, Litton Loan",11700.0,MAIDEN,NaN,4828.0,"Loop Central Dr., 3rd Floor",Houston,...,0.0,0.0,0.0,0.0,NaN,NO PAYMENT APPLIED,NaN,NaN,not responsible by disposition,-1.0
197756,197756,"Buildings, Safety Engineering & Env Department","O'Neal, Claude","BAILEY, JAMES",10075.0,BEECHDALE,NaN,16972.0,KINLOCH,REDFORD,...,0.0,305.0,305.0,0.0,2009-03-18 00:00:00,PAID IN FULL,NaN,NaN,compliant by late payment within 1 month,1.0
270803,270803,"Buildings, Safety Engineering & Env Department","Morris, John","WARREN, FLYNN",5984.0,LINCOLN,NaN,211.0,WHITE,PORT HURON,...,0.0,305.0,0.0,305.0,NaN,NO PAYMENT APPLIED,NaN,NaN,non-compliant by no payment,0.0

In [64]:
y = train[train.compliance != -1]

In [65]:
y_value = y.compliance

In [66]:
y_value.head()

ticket_id
22056    0.0
27586    1.0
22046    0.0
18738    0.0
18735    0.0
Name: compliance, dtype: float64

In [67]:
x.fillna(value = -1)

,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount
ticket_id,,,,,,,
22056,250.0,20.0,10.0,25.0,0.0,0.0,305.0
27586,750.0,20.0,10.0,75.0,0.0,0.0,855.0
22062,250.0,0.0,0.0,0.0,0.0,0.0,0.0
22084,250.0,0.0,0.0,0.0,0.0,0.0,0.0
22093,250.0,0.0,0.0,0.0,0.0,0.0,0.0
22046,250.0,20.0,10.0,25.0,0.0,0.0,305.0
18738,750.0,20.0,10.0,75.0,0.0,0.0,855.0
18735,100.0,20.0,10.0,10.0,0.0,0.0,140.0
18733,100.0,20.0,10.0,10.0,0.0,0.0,140.0
28204,750.0,20.0,10.0,75.0,0.0,0.0,855.0
18739,750.0,0.0,0.0,0.0,0.0,0.0,0.0
18740,100.0,0.0,0.0,0.0,0.0,0.0,0.0
18743,750.0,20.0,10.0,75.0,0.0,0.0,855.0
18741,750.0,20.0,10.0,75.0,0.0,0.0,855.0
18978,750.0,20.0,10.0,75.0,0.0,0.0,855.0
18974,750.0,0.0,0.0,0.0,0.0,0.0,0.0
18742,750.0,0.0,0.0,0.0,0.0,0.0,0.0
28211,750.0,0.0,0.0,0.0,0.0,0.0,0.0
18746,100.0,20.0,10.0,10.0,0.0,0.0,140.0
18744,100.0,20.0,10.0,10.0,0.0,0.0,140.0
18747,100.0,0.0,0.0,0.0,0.0,0.0,0.0
26846,750.0,20.0,10.0,75.0,0.0,0.0,855.0
26848,750.0,20.0,10.0,75.0,0.0,0.0,855.0
28209,750.0,20.0,10.0,75.0,0.0,0.0,855.0
18736,100.0,0.0,0.0,0.0,0.0,0.0,0.0
18737,100.0,0.0,0.0,0.0,0.0,0.0,0.0
19950,100.0,20.0,10.0,0.0,0.0,0.0,130.0
19311,3500.0,0.0,0.0,0.0,0.0,0.0,0.0
18645,250.0,20.0,10.0,25.0,0.0,0.0,305.0
19310,3500.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
285037,100.0,20.0,10.0,10.0,0.0,0.0,140.0
285034,500.0,20.0,10.0,50.0,0.0,0.0,580.0
285106,200.0,20.0,10.0,20.0,0.0,0.0,250.0
285040,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
285042,50.0,0.0,0.0,0.0,0.0,0.0,0.0
285097,500.0,0.0,0.0,0.0,0.0,0.0,0.0
285098,50.0,0.0,0.0,0.0,0.0,0.0,0.0
284740,250.0,0.0,0.0,0.0,0.0,0.0,0.0
284877,250.0,0.0,0.0,0.0,0.0,0.0,0.0
284879,200.0,0.0,0.0,0.0,0.0,0.0,0.0
284880,200.0,0.0,0.0,0.0,0.0,0.0,0.0
284650,1000.0,20.0,10.0,100.0,0.0,0.0,1130.0
285125,500.0,20.0,10.0,50.0,0.0,0.0,580.0
284647,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
284881,200.0,20.0,10.0,0.0,0.0,0.0,230.0
284878,200.0,0.0,0.0,0.0,0.0,0.0,0.0
284338,200.0,0.0,0.0,0.0,0.0,0.0,0.0
284333,200.0,20.0,10.0,20.0,0.0,0.0,250.0
284882,100.0,0.0,0.0,0.0,0.0,0.0,0.0
284883,100.0,0.0,0.0,0.0,0.0,0.0,0.0
366178,100.0,0.0,0.0,0.0,0.0,0.0,0.0
366176,250.0,0.0,0.0,0.0,0.0,0.0,0.0
325560,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
325556,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
325558,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
325555,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
325557,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
325562,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
325559,1000.0,0.0,0.0,0.0,0.0,0.0,0.0
325561,1000.0,0.0,0.0,0.0,0.0,0.0,0.0

In [68]:
x = y[features]

In [69]:
#Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y_value, random_state = 0)

In [70]:
#Compiling the model (Random Forest)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators = 10, max_depth = 5).fit(X_train, y_train)

In [83]:
#Importing test data
test_data = pd.read_csv('readonly/test.csv')

In [84]:
test_data.head()

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,violation_description,disposition,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,grafitti_status
0,284932,Department of Public Works,"Granberry, Aisha B","FLUELLEN, JOHN A",10041.0,ROSEBERRY,NaN,141,ROSEBERRY,DETROIT,...,Failure to secure City or Private solid waste ...,Responsible by Default,200.0,20.0,10.0,20.0,0.0,0.0,250.0,NaN
1,285362,Department of Public Works,"Lusk, Gertrina","WHIGHAM, THELMA",18520.0,EVERGREEN,NaN,19136,GLASTONBURY,DETROIT,...,Allowing bulk solid waste to lie or accumulate...,Responsible by Default,1000.0,20.0,10.0,100.0,0.0,0.0,1130.0,NaN
2,285361,Department of Public Works,"Lusk, Gertrina","WHIGHAM, THELMA",18520.0,EVERGREEN,NaN,19136,GLASTONBURY,DETROIT,...,Improper placement of Courville container betw...,Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,NaN
3,285338,Department of Public Works,"Talbert, Reginald","HARABEDIEN, POPKIN",1835.0,CENTRAL,NaN,2246,NELSON,WOODHAVEN,...,Allowing bulk solid waste to lie or accumulate...,Responsible by Default,200.0,20.0,10.0,20.0,0.0,0.0,250.0,NaN
4,285346,Department of Public Works,"Talbert, Reginald","CORBELL, STANLEY",1700.0,CENTRAL,NaN,3435,MUNGER,LIVONIA,...,Violation of time limit for approved container...,Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,NaN

In [85]:
test_data.index = test_data['ticket_id']

In [86]:
test_data.sample(5)

,ticket_id,agency_name,inspector_name,violator_name,violation_street_number,violation_street_name,violation_zip_code,mailing_address_str_number,mailing_address_str_name,city,...,violation_description,disposition,fine_amount,admin_fee,state_fee,late_fee,discount_amount,clean_up_cost,judgment_amount,grafitti_status
ticket_id,,,,,,,,,,,,,,,,,,,,,
320623,320623,Department of Public Works,"Askew, Marcus","TRANSPORTATION, CSX",15000.0,FULLERTON,NaN,5,WATER STREET,JACKSONVILLE,...,Allowing bulk solid waste to lie or accumulate...,Responsible by Default,200.0,20.0,10.0,20.0,0.0,0.0,250.0,NaN
339717,339717,"Buildings, Safety Engineering & Env Department","FLEMINGS, SAMUEL",BRIDGEPORT MANAGEMENT LLC,12145.0,MORANG,48224,1862,W. 10 MILE RD. STE 110,SOUTHFIELD,...,Failure of owner to remove graffiti or maintai...,Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,GRAFFITI TICKET
294188,294188,Department of Public Works,"McClain, Melvin","BAKER, JR., RONALD",3273.0,ELMHURST,NaN,477,23RD ST.,DETROIT,...,Allowing bulk solid waste to lie or accumulate...,Responsible by Default,2500.0,20.0,10.0,250.0,0.0,0.0,2780.0,NaN
329270,329270,Department of Public Works,"Snyder, Derrell","Jones, Ryan",16256.0,ROBSON,48235,16624,Birwood,Detroit,...,"Failure of owner to keep property, its sidewal...",Responsible by Default,100.0,20.0,10.0,10.0,0.0,0.0,140.0,NaN
331794,331794,"Buildings, Safety Engineering & Env Department","Bush, Wesley",WESTGATE TERRACE APARTMENTS LLC,10721.0,SANTA MARIA,NaN,39,CENTENNIAL DRIVE,MIDLAND,...,Failure of owner to obtain certificate of comp...,Responsible by Determination,250.0,20.0,10.0,25.0,0.0,0.0,305.0,NaN

In [93]:
train_score = model.score(X_train, y_train)
test_score = model.score(X_test, y_test)

print('Training score: ' + str(train_score) + '       Testing score: ' + str(test_score))

Training score: 0.935635059628       Testing score: 0.934575931949

In [87]:
prediction = model.predict_proba(test_data[features])

In [88]:
prediction

array([[ 0.9329824 ,  0.0670176 ],
       [ 0.96908539,  0.03091461],
       [ 0.93073411,  0.06926589],
       ...,
       [ 0.93073411,  0.06926589],
       [ 0.93073411,  0.06926589],
       [ 0.74123131,  0.25876869]])

In [89]:
compliance_prob = pd.Series(data = prediction[:,1], index = test_data['ticket_id'], dtype = 'float32')

In [90]:
compliance_prob

ticket_id
284932    0.067018
285362    0.030915
285361    0.069266
285338    0.067018
285346    0.069266
285345    0.067018
285347    0.059460
285342    0.300255
285530    0.030915
284989    0.031372
285344    0.059460
285343    0.030915
285340    0.030915
285341    0.059460
285349    0.069266
285348    0.067018
284991    0.031372
285532    0.031372
285406    0.031372
285001    0.031372
285006    0.030915
285405    0.030915
285337    0.031372
285496    0.059460
285497    0.067018
285378    0.030915
285589    0.031372
285585    0.067018
285501    0.069266
285581    0.030915
            ...
376367    0.031372
376366    0.035547
376362    0.035547
376363    0.067018
376365    0.031372
376364    0.035547
376228    0.035547
376265    0.035547
376286    0.312337
376320    0.035547
376314    0.035547
376327    0.312337
376385    0.312337
376435    0.310354
376370    0.312337
376434    0.059460
376459    0.069266
376478    0.007305
376473    0.035547
376484    0.027765
376482    0.031372
376480    0.031372
376479    0.031372
376481    0.031372
376483    0.035547
376496    0.030915
376497    0.030915
376499    0.069266
376500    0.069266
369851    0.258769
dtype: float32